/* eslint-disable no-undef */
describe('Grabit', () => {
  it('can visits the app, and edits the profile', () => {
    cy.visit('/')
      .findByText(/^Sign In$/)
      .click()
      .findByText(/Continue with facebook/i)
      .click()
      .get('#profile')
      .click()
      .findByLabelText('Name')
      .focus()
      .clear()
      .type('Mourad Not Aouinat')
      .findByLabelText('Phone')
      .focus()
      .clear()
      .type('0690092626')
      .clear()
      .type('+212690092625')
      .findByText(/^Update$/)
      .focus()
      .click()
  })
})
