/* eslint-disable no-undef */
describe('Grabit', () => {
  it('can visits the app, signs in and places an order', () => {
    cy.visit('/')
      .findByText(/^Sign In$/)
      .click()
      .findByText(/Continue with facebook/i)
      .click()
      .findByLabelText(/Describe your order/i)
      .focus()
      .type('I want to get some good stuff please')
      .findByPlaceholderText(/add item/i)
      .focus()
      .type('cool whip')
      .findByText(/^Add$/)
      .click()
      .findByPlaceholderText(/ASAP/)
      .focus()
      .type('ASAP')
      .findByPlaceholderText('$50 - $60')
      .focus()
      .type('100 - 120')
      .findByPlaceholderText(/Set the order location/i)
      .focus()
      .type('55 afka kenitra')
      .findByPlaceholderText(/Set the order destination/i)
      .focus()
      .type('47, Avenue Atlas, Agdal Rabat, Morocco')
      .findByText('Request')
      .focus()
      .click()
  })
})
